version = 0.1
[default.deploy.parameters]
stack_name = "comparison-cloud-function-snap-start"
resolve_s3 = true
s3_prefix = "comparison-cloud-function-snap-start"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
