AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zip

  Sample SAM Template for zip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  AWSCloudFunctionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java21
      Architectures:
        - arm64
      MemorySize: 512
#      SnapStart:
#        ApplyOn: "PublishedVersions"
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
          MAIN_CLASS: com.mikescherbakov.awslambdaspringbootdemocomparison.AwsLambdaSpringBootDemoComparisonApplication
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable

      Events:
        AWSCloudFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AWSCloudFunctionFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for AWSCloudFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  AWSCloudFunctionFunction:
    Description: "AWSCloudFunction Lambda Function ARN"
    Value: !GetAtt AWSCloudFunctionFunction.Arn
  AWSCloudFunctionFunctionIamRole:
    Description: "Implicit IAM Role created for AWSCloudFunction function"
    Value: !GetAtt AWSCloudFunctionFunctionRole.Arn
  AWSCloudFunctionDynamoDbTable:
    Value: !Ref DynamoTable
    Description: DynamoDb Table
