AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zip

  Sample SAM Template for zip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  AWSSpringBootGraalVMFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: not.used.in.provided.runtime
      CodeUri: aws/lambda/dist/aws-lambda-spring-boot-demo-comparison_aarch64.zip
      Runtime: provided.al2023
      Architectures:
        - arm64
      MemorySize: 512
#      SnapStart:
#        ApplyOn: "PublishedVersions"
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable

      Events:
        AWSSpringBootGraalVM:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AWSSpringBootGraalVMFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for AWSSpringBootGraalVM function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  AWSSpringBootGraalVMFunction:
    Description: "AWSSpringBootGraalVM Lambda Function ARN"
    Value: !GetAtt AWSSpringBootGraalVMFunction.Arn
  AWSSpringBootGraalVMFunctionIamRole:
    Description: "Implicit IAM Role created for AWSSpringBootGraalVM function"
    Value: !GetAtt AWSSpringBootGraalVMFunctionRole.Arn
  AWSSpringBootGraalVMDynamoDbTable:
    Value: !Ref DynamoTable
    Description: DynamoDb Table
